# Identifiant unique du projet
sonar.projectKey=distance-api-project
sonar.projectName=Distance API Refactoring

# Dossier à analyser (le dossier courant)
sonar.sources=.
# On exclut les fichiers de tests de l'analyse du code source (pour ne pas fausser la dette technique)
sonar.exclusions=test_app.py

# Dossier contenant les tests
sonar.tests=.
# On inclut uniquement les fichiers de tests ici
sonar.test.inclusions=test_app.py

# Chemin vers le rapport de couverture que pytest va générer
sonar.python.coverage.reportPaths=coverage.xml